env:
  es2021: true
  node: true
extends:
  - airbnb
  - airbnb-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 15
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules: 
  no-console: off
  import/extensions: off

